const config = {
    preferences: {
        defaultLanguage : 'en-US',
        defaultConvertType : 'sentence',
        defaultConvertedText : `LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT. VIVAMUS IN COMMODO IPSUM, DAPIBUS SOLLICITUDIN ERAT. IN HAC HABITASSE PLATEA DICTUMST. DONEC ID MAURIS EGET LEO CURSUS ORNARE. NAM UT ARCU IACULIS, PORTTITOR LOREM UT, COMMODO TURPIS. UT ELEMENTUM SAPIEN AT CONGUE ACCUMSAN. SUSPENDISSE URNA ODIO, DIGNISSIM NON TEMPUS VITAE, PULVINAR QUIS RISUS. AENEAN LACINIA LOREM NUNC, VITAE ORNARE DUI BIBENDUM UT. PRAESENT UT RISUS AT TURPIS HENDRERIT RUTRUM QUIS NEC JUSTO. NAM SUSCIPIT VIVERRA AUGUE, AT VESTIBULUM NISI CURSUS AT. ALIQUAM SCELERISQUE, ANTE SIT AMET ORNARE FEUGIAT, EROS LECTUS TINCIDUNT TURPIS, VITAE VARIUS TORTOR FELIS AT DOLOR. PRAESENT LUCTUS TURPIS AC LOREM TEMPOR LOBORTIS.
                                \nNUNC AC EROS EGET NUNC DAPIBUS FRINGILLA QUIS QUIS DIAM. QUISQUE VEHICULA PURUS ODIO, NON HENDRERIT SAPIEN VEHICULA SIT AMET. NULLAM AT SOLLICITUDIN MAGNA. NULLA CONDIMENTUM UT MAGNA AT PELLENTESQUE. IN HAC HABITASSE PLATEA DICTUMST. NUNC QUIS ODIO VEL ORCI VOLUTPAT SUSCIPIT NON UT URNA. UT RHONCUS SAPIEN SED TELLUS LAOREET, A VESTIBULUM METUS SCELERISQUE.
                                \nQUISQUE ULLAMCORPER LIGULA AC DOLOR PORTA ALIQUAM. IN PORTA VEHICULA DIGNISSIM. NULLA FACILISIS FRINGILLA LIBERO, SIT AMET ELEIFEND NEQUE FEUGIAT VITAE. DONEC CONSEQUAT QUAM VEL SODALES CONGUE. NULLA MOLLIS, NUNC SIT AMET CONSECTETUR EFFICITUR, NUNC ORCI BLANDIT ERAT, SIT AMET TINCIDUNT IPSUM SEM LACINIA LIBERO. UT A DUI ULTRICES, FACILISIS MI VEL, CONSEQUAT NUNC. NULLA ID NULLA TEMPUS, HENDRERIT ELIT EGET, RUTRUM TORTOR. DUIS FAUCIBUS NISI AT CONGUE ULTRICIES. IN HAC HABITASSE PLATEA DICTUMST.`,
    },
}

export default config;